### ISSUE TITLE
A few questions about next_geq function

### ISSUE THREAD

**Issue by lxy-9602** [jermp/s_indexes#1]
Hello, I do appreciate your clear and well-organized code. But I have a little question. 

On line 184 of the next_geq.hpp, after calling the next() function, do we need to check whether it has_next() and then perform the CHUNK_MIN operation? I tested the orignal code with example. If we operate ss.next_geq(x+1), where x is the maximum docID of sequence ss, it will return 0 instead of constants::not_found.

Sorry if I misunderstanding the code.

**Comment by jermp** [comment]
Hi, thanks for the kind words.

Yes, you are right and I fixed the issue.
See the updated `test/test_next_geq.cpp` file and `test/test_next_geq_enumerator.cpp`:
now they return correctly constants::not_found whenever lower_bound > universe.
Thanks.
