### ISSUE TITLE
Actual intersection set instead of just size of the set

### ISSUE THREAD

**Issue by Dhrumil2910** [jermp/s_indexes#2]
Hi,
The code is well documented. I just have two queries:

- How to get the actual intersection and union output between two sequences instead of just getting the size of the final output?

- If the above thing is possible, then is the final intersection and union output in the compressed form or decompressed?

**Comment by jermp** [comment]
Hi,
just from the readme:

/* writes the result of the intersection between the
   sequences to the output buffer, returning the size of the result */
size_t intersection(std::vector<s_sequence>& sequences, uint32_t* out);

/* writes the result of the union between the
   sequences to the output buffer, returning the size of the result */
size_t union_many(std::vector<s_sequence>& sequences, uint32_t* out);

so the actual intersection and union get materialized into the output buffer, reference by the out pointer.
The output buffer is always assumed to be uncompressed.
